config/routes.rb
Hotels::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: '/', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  namespace :catalogue do
    get 'dashboard/index'
    resources :raitings, only: [:create, :update]
    resources :comments, only: :create
    resources :hotels, only: [:index, :show, :create, :new]
  end

  root to: 'catalogue/dashboard#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  belongs_to :hotel

  validates :body, presence: true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  STATUSES = { default: 'pending', approved: 'approved', rejected: 'rejected' }
  serialize :address, Hash

  belongs_to :author, class_name: 'User', foreign_key: 'author_id', counter_cache: true
  has_many   :comments, include: :user
  has_many   :raitings
  has_many   :raters, through: :raitings, source: :user

  validates :title,
            presence: true,
            uniqueness: { case_sensitive: false},
            length: { maximum: 75 }
  validates :price_for_room,
            numericality: { greater_than: 0 },
            allow_nil: true
  validates :status,
            inclusion: { in: STATUSES.values },
            allow_blank: false,
            on: :update

  scope :approved,  -> { where(status: 'approved') }
  scope :rejected,  -> { where(status: 'rejected') }
  scope :pending,   -> { where(status: 'pending') }

  before_create :set_default_status

  mount_uploader :photo, PhotoUploader

  def set_default_status
    self.status = STATUSES[:default]
  end

  def average_rating
    @rate = 0
    self.raitings.each do |raiting|
      @rate += raiting.score
    end
    @total = self.raitings.size
    @rate.to_f / @total.to_f
  end

end

app/models/raiting.rb
class Raiting < ActiveRecord::Base
  belongs_to :user, counter_cache: true
  belongs_to :hotel
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :hotels, foreign_key: 'author_id'
  has_many :comments
  has_many :raitings
  has_many :rated_hotels, through: :raitings, source: :hotel

  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catalogue/application_controller.rb
class Catalogue::ApplicationController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/catalogue/comments_controller.rb
class Catalogue::CommentsController < Catalogue::ApplicationController
  inherit_resources
  actions :new, :create

  def create
    @comment = current_user.comments.build(comment_params)
    create! do |success, failure|
      success.html {
        redirect_to catalogue_hotel_url(comment_params[:hotel_id]),
                    notice: 'Your comment added.'
      }
      failure.html {
        flash[:error] = 'Adding comment aborted! wright something, please!'
        redirect_to catalogue_hotel_url(comment_params[:hotel_id])
      }
    end
  end

  protected

  def comment_params
    params.require(:comment).permit!.except(:user_id)
  end
end

app/controllers/catalogue/dashboard_controller.rb
class Catalogue::DashboardController < Catalogue::ApplicationController
  def index
  end
end

app/controllers/catalogue/hotels_controller.rb
class Catalogue::HotelsController < Catalogue::ApplicationController
  inherit_resources
  actions :index, :show, :new, :create

  def create
    @hotel = current_user.hotels.build(hotel_params)
    create! do |success, failure|
      success.html {
        redirect_to catalogue_hotels_url,
        notice: 'Your hotel added. Expect to administrator confirm your request'
      }
      failure.html {
        flash[:error] = 'Adding aborted! Check your hotel data'
        render action: 'new'
      }
    end
  end

  protected
    def collection
      @hotels ||= end_of_association_chain.approved
    end

    def hotel_params
      params.require(:hotel).permit!.except(:author_id)
    end
end

app/controllers/catalogue/raitings_controller.rb
class Catalogue::RaitingsController < Catalogue::ApplicationController
  before_action :set_hotel, only: [:create, :update]

  def create
    if current_user.id == @hotel.author.id
      redirect_to catalogue_hotel_path(@hotel), alert: 'You cannot rate for your own hotel'
    else
      @rating = Raiting.new(raiting_params)
      @rating.hotel_id = @hotel.id
      @rating.user_id = current_user.id
      if @rating.save
        respond_to do |format|
          format.html { redirect_to catalogue_hotel_path(@hotel), notice: 'Your rating has been saved' }
          format.js
        end
      end
    end
  end

  def update
    if current_user.id == @hotel.author.id
      redirect_to catalogue_hotel_url(@hotel), alert: 'You cannot rate for your own hotel'
    else
      @rating = current_user.raitings.find_by_hotel_id(@hotel.id)
      if @rating.update_attributes(raiting_params)
        respond_to do |format|
          format.html { redirect_to catalogue_hotel_url(@hotel), notice: 'Your rating has been updated' }
          format.js
        end
      end
    end
  end

  protected

  def raiting_params
    params.require(:raiting).permit!.except(:user_id)
  end

  def set_hotel
    @hotel = Hotel.find_by_id(raiting_params[:hotel_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotel_helper.rb
module HotelHelper
  def rating_score
    if @rating = current_user.raitings.find_by_hotel_id(params[:id])
      @rating
    else
      current_user.raitings.new
    end
  end

  def current_user_rating
    if @rating = current_user.raitings.find_by_hotel_id(params[:id])
      @rating.score
    else
      'N/A'
    end
  end
end

app/views/catalogue/dashboard/index.html.haml
%h1 Hotels::Dashboard#index
%p Find me in app/views/layouts/dashboard/index.html.haml

app/views/catalogue/hotels/_add_comment.html.haml
%h2.text-muted Leave comment :
%hr
= form_for [:catalogue, Comment.new], html: {class: 'form-horizontal'} do |f|
  = f.hidden_field :hotel_id, value: @hotel.id
  .form-group
    = f.label :body, class: 'control-label'
    = f.text_area :body, class: 'form-control col-md-12', style: "resize: none", rows: 5
  .form-group
    = f.submit 'Comment', class: 'btn btn-success'

app/views/catalogue/hotels/_comments.html.haml
%h2.text-muted
  Comments
  %span.badge= comments.size
%hr
- if comments.present?
  - comments.each do |comment|
    .comment
      .text-muted #{comment.user.email}  |  #{comment.created_at}
      %p= comment.body
- else
  %p.text-warning
    There are no comments yet! :/

app/views/catalogue/hotels/_hotel.html.haml
.col-md-4.hotel-item
  = image_tag hotel.photo.thumb.url, class: 'img-circle'
  %h2= link_to hotel.title, catalogue_hotel_path(hotel)
  %p= hotel.room_description.html_safe
  = link_to 'View Details >>', catalogue_hotel_path(hotel), class: 'btn btn-default'

app/views/catalogue/hotels/_raiting_form.html.haml
= form_for([:catalogue, rating_score], html: { class: 'rating_score' }) do |f|
  = f.label('value_1', content_tag(:span, '1'), {class: 'rating', id: '1'})
  = radio_button_tag('raiting[score]', 1, current_user_rating == 1, class: 'rating_button')
  = f.label('value_2', content_tag(:span, '2'), {class: 'rating', id: '2'})
  = radio_button_tag('raiting[score]', 2, current_user_rating == 2, class: 'rating_button')
  = f.label('value_3', content_tag(:span, '3'), {class: 'rating', id: '3'})
  = radio_button_tag('raiting[score]', 3, current_user_rating == 3, class: 'rating_button')
  = f.label('value_4', content_tag(:span, '4'), {class: 'rating', id: '4'})
  = radio_button_tag('raiting[score]', 4, current_user_rating == 4, class: 'rating_button')
  = f.label('value_5', content_tag(:span, '5'), {class: 'rating', id: '5'})
  = radio_button_tag('raiting[score]', 5, current_user_rating == 5, class: 'rating_button')

  = f.hidden_field :hotel_id , value: @hotel.id
  = f.submit 'Rate', class: 'btn btn-default'

app/views/catalogue/hotels/index.html.haml
%h1.h1-hotels
  Hotels
  %span.badge= @hotels.size
%hr
.row
  = render @hotels

app/views/catalogue/hotels/new.html.haml
%h1 Add your hotel:
= form_for [:catalogue, @hotel], html: {class: 'form-horizontal'} do |f|
  %h3.text-primary Hotel info:
  .form-group
    = f.label :title, class: 'control-label'
    %br/
    = f.text_field :title, autofocus: true, class: 'form-control'
  .form-group
    = f.label :room_description, class: 'control-label'
    = f.cktext_area :room_description, ckeditor: {toolbar: 'mini'}
  .form-group
    = f.label :breakfast, class: 'control-label'
    = f.check_box :breakfast, checked: true
  .form-group
    = f.label :price_for_room, class: 'control-label'
    = f.text_field  :price_for_room,
                    type: :number,
                    maxlength: 10,
                    placeholder: '0.00',
                    step: 0.2,
                    min: 0,
                    class: 'form-control'
  .form-group
    %label Photo :
    = image_tag(@hotel.photo_url) if @hotel.photo?
    = f.file_field :photo
  %h3.text-primary Hotel address:
  = f.fields_for :address do |address_form|
    .form-group
      %label.control-label Country :
      = address_form.text_field :country, placeholder: 'Enter location', class: 'form-control'
    .form-group
      %label.control-label City :
      = address_form.text_field :city, placeholder: 'Enter location', class: 'form-control'
    .form-group
      %label.control-label Street :
      = address_form.text_field :street, placeholder: 'Enter location', class: 'form-control'
  .form-group
    = f.submit 'Add hotel', class: 'btn btn-default btn-lg'

app/views/catalogue/hotels/show.html.haml
.row
  %h1.h1-hotels
    Hotel:
    %span.text-primary= @hotel.title
  %hr
  .col-md-8.col-md-offset-2.hotel-show
    = image_tag @hotel.photo.orig.url, class: 'thumbnail'
    %p.text-muted
      Location :
      = @hotel.address.blank? ? @hotel.address.values.join(', ') : 'Somewere'
    .text-muted= @hotel.room_description.html_safe
    %p.text-muted
      Breakfast
      - if @hotel.breakfast
        .label.label-success Yes
      - else
        .label.label-warning No
    %h3.text-success
      Price :
      .label.label-success= number_to_currency @hotel.price_for_room
    %p.text-muted
      Current rate is #{@hotel.average_rating}, rate by #{@hotel.raters.size}
      - if user_signed_in?
        %table.table.table-condensed
          %thead
            %tr
              %th{ colspan: 2 }
                Hotel Rating
            %tr.warning
              %td Average Rating
              %td= @hotel.average_rating
            %tr.info
              %td Your Rating
              %td= current_user_rating
        = render 'raiting_form'
      - if @hotel.raters.present?
        This hotel rated by #{@hotel.raters.size} users :
        %p.text-primary
          = @hotel.raters.map(&:email).join(', ')
      - else
        %p.text-warning Nobody rated #{@hotel.title}
    %p.text-muted
      Added
      %span.text-primary
        = @hotel.created_at
      by
      %span.text-primary
        = @hotel.author.email
.row
  = render partial: 'comments', locals: { comments: @hotel.comments }
.row
  - if user_signed_in?
    = render partial: 'add_comment'
  - else
    %p.text-warning
      "Please #{link_to 'sign in', new_user_session_path} or #{link_to 'register', new_user_registration_path} to leave comment for this hotel"

app/views/layouts/application.html.haml
%html(lang= "en")
  %head
    %title Hotels
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
%body
  / Site header
  = render 'shared/header'
  / Container
  .container-fluid
    / Alerts
    .row-fluid
      = render 'shared/flash' unless flash.blank?
    / Data
    .row-fluid
      .col-md-10.col-md-offset-1
        = yield

app/views/shared/_flash.html.haml
.container
  - flash.each do |key,value|
    = content_tag(:div, "Message: #{value}", class: 'bg-warning col-md-4 col-md-offset-4')

app/views/shared/_header.html.haml
.navbar.navbar-default{role: 'navigation'}
  .container-fluid
    .navbar-header
      = link_to 'Dashboard', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li= link_to 'Hotels', catalogue_hotels_url
        %li= link_to 'About', '#'
        %li= link_to 'Help', '#'

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.active= link_to("Logout (#{current_user.email})", destroy_user_session_path, method: :get)
          %li= link_to('Edit registration', edit_user_registration_path)
          %li= link_to('Add hotel', new_catalogue_hotel_path)
        - else
          %li.active= link_to('Login', new_user_session_path)
          %li= link_to('Register', new_user_registration_path)

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/